export const  ACCESS_TOKEN = "@accessToken"
export const REFRESH_TOKEN = "@refreshToken"
export const USER_ID="@userId"
export const HOME_SCREEN = "Home"
export const TAB_NAV_SCREEN = "TabNav"
export const MY_CONF_SCREEN = "MyConf"
export const VIEW_SCHEDULE="View Schedule"
export const LOGIN_SCREEN = "Login"
